slice_name: GA Filtered Metrics Example Line Chart
viz_type: echarts_timeseries_line
params:
  datasource: 69__table
  viz_type: echarts_timeseries_line
  slice_id: 239
  x_axis: Date
  time_grain_sqla: P1D
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Value
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1786
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(Value)
    optionName: metric_45khe00v2nb_m9ja3goue0q
    sqlExpression: null
  groupby:
  - Metric
  adhoc_filters:
  - expressionType: SIMPLE
    subject: Date
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    comparator: 'DATEADD(DATETIME("now"), -90, day) : now'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_2x1g9gmshjb_6rzwytgmsdl
  emit_filter: true
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  time_compare:
  - 4 weeks ago
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: my-example-color-pallete
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 37
cache_timeout: null
uuid: d7cf5e5d-a7ef-42d9-9916-3d2ee0f736d3
version: 1.0.0
dataset_uuid: 8516dfea-7cfe-496b-a858-666f16aca378
